lang: ruby
rvm:
- 2.3.6
bundler_args: "--system"
env:
  global:
  - GH_REF: github.com/idodin/interview-prep-guide
branches:
  only:
  - master
script:
- ./render.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
